app:
  name: "GinDemo"
  port: 8080

db:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  name: "bbs"
  # 数据库连接池配置
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

cache:
  article_expire: 600
  like_expire: 3600

# JWT配置
jwt:
  secret: "your_super_secret_jwt_key_change_in_production"
  expire_hours: 24